services:
  
  usersDb:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: usersDb
    environment:
      SA_PASSWORD: "password1!"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'password1!' -Q 'select 1'" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - users-network
   
  userservice.api:
    container_name: userservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__ConnectionString=Server=usersDb;Database=usersDb;User Id=sa;Password=password1!;TrustServerCertificate=True"
    image: userservice.api
    build:
      context: .
      dockerfile: UserService.API/Dockerfile
    depends_on:
      - usersDb
    ports:
      - "8003:8080"
    command: >
      /bin/sh -c "dotnet ef database update -p ../UserService.Infrastructure -s ../UserService.API && dotnet UserService.API.dll"
      
    networks:
      - users-network

networks:
  users-network:
    driver: bridge