services:
  usersdb:
    container_name: usersdb
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - orderdb-data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'password' -Q 'select 1'" ]
      interval: 10s
      timeout: 10s
      retries: 3
  
  userservice.api:
    image: userservice.api
    build:
      context: .
      dockerfile: UserService.API/Dockerfile
    depends_on:
      - usersdb
